In [ ]:
#Basics Of Numpy


In [1]:
import numpy as np

In [2]:
n1=np.array([10,20,30,40,50,60])

In [5]:
n1

array([10, 20, 30, 40, 50, 60])

In [6]:
#Multi Dimensional array

In [10]:
n2=np.array([[10,20,30],[40,50,60]])

In [11]:
n2

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
#initializing numpy array
#initializing numpy array with zero
#they show us to how much we need row and column.

In [15]:
n1=np.zeros((1,2))

In [16]:
n1

array([[0., 0.]])

In [17]:
n1=np.zeros((5,6))

In [18]:
n1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
#initializing numpy array with same number
#in full method we also give the numbers for making a row and column

In [21]:
n1=np.full((5,6),10)

In [22]:
n1

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [24]:
#initializing numpy with range

In [25]:
n1=np.arange(10,20)

In [26]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
n1=np.arange(10,530,10)

In [32]:
n1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390,
       400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520])

In [33]:
#initializing numpy with random number


In [36]:
n1=np.random.randint(1,100,10)

In [44]:
n1


array([25, 91, 53, 91, 76, 85, 13, 38, 73, 58])

In [46]:
#checking the shape of numpy arrays

In [51]:
n1=np.array([[1,2,3],[4,5,6]])

In [52]:
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
n1.shape

(2, 3)

In [60]:
#how to join 2 numpy array
#use vstack
#first we have to make 2 array

In [67]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

n1

In [69]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [70]:
#now study about hstack
#hstach means horizontal stack

In [71]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

In [73]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [74]:
#column stack

In [75]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

In [78]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [79]:
#how to find common element in numpy array


In [83]:
n1=np.array([10,40,30])
n2=np.array([30,50,40])

In [84]:
np.intersect1d(n1,n2)

array([30, 40])

In [85]:
#how to delete common element from numpy array.

In [86]:
n1=np.array([10,20,30,40,50,60,10,20,30,10,40,50,60])
n2=np.array([10,70,80,90,58,69,10,50,60,40,50,98,78])

In [90]:
np.setdiff1d(n1,n2) #thats not work properly

array([20, 30])

In [92]:
#if we have to minus n2-n1
#we can use setdiff1d but use minus - sign in the place ','
#see with exmaple

In [94]:
n1=np.array([10,20,30])
n2=np.array([17,16,15])

In [101]:
np.setdiff1d(n1,-n2)

array([10, 20, 30])

In [107]:
#addition of numpy in column

In [108]:
n1=np.array([10,20,30])
n2=np.array([20,30,40])

In [109]:
np.sum([n1,n2],axis=0)

array([30, 50, 70])

In [110]:
#addition in rows

In [111]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

In [112]:
np.sum([n1,n2],axis=1)

array([ 60, 150])

In [5]:
import numpy as np

In [1]:
#Basic addition

In [6]:
n1=np.array([10,20,30,40])

In [8]:
n1=n1+1

In [11]:
n1

array([11, 21, 31, 41])

In [12]:
#Basic multiplication

In [13]:
n1=np.array([2,4,5,6])

In [14]:
n1=n1*2

In [15]:
n1

array([ 4,  8, 10, 12])

In [16]:
#Basic Division

In [18]:
n1=np.array([4,8,6,12])

In [19]:
n1=n1/2

In [20]:
n1

array([2., 4., 3., 6.])

In [21]:
#Basic Subtraction

In [22]:
n1=np.array([8,4,12,16,18])

In [23]:
n1=n1-2

In [24]:
n1

array([ 6,  2, 10, 14, 16])

In [25]:
#Mean

In [26]:
n1=np.array([10,20,30,50,40])

In [27]:
n1

array([10, 20, 30, 50, 40])

In [28]:
np.mean(n1)

30.0

In [29]:
#median

In [30]:
n1

array([10, 20, 30, 50, 40])

In [31]:
np.median(n1)

30.0

In [32]:
#Standard Division

In [33]:
n1

array([10, 20, 30, 50, 40])

In [35]:
np.std(n1)

14.142135623730951

In [36]:
#Saving Numpy Array

In [37]:
n1

array([10, 20, 30, 50, 40])

In [48]:
n2=np.save('my_numpy',n1)

In [49]:
#Basics Of Numpy
#Student Of Data Science - Saurav
# Datatrained 
#Batch np- DS0522